---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: false
  tasks:
    - name: assurance settings
      cisco.dnac.assurance_settings_workflow_manager:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config_verify: true
        config:
          - assurance_issue:
              - issue_name: "Excessive time lag between Cisco Catalyst Center and device \"DC-T-9300\""
                issue_process_type: ignore
          - assurance_user_defined_issue_settings:
              - name: ippo
                description: testing settings 1
                rules:
                  - severity: 1
                    facility: redundancy
                    mnemonic: peer monitor event
                    pattern: issue test
                    occurrences: 4
                    duration_in_minutes: 6
                is_enabled: true
                priority: P1
                is_notification_enabled: false
                prev_name: create4

          - assurance_system_issue_settings:
              - name: AP Reboot Crash
                device_type: UNIFIED_AP
                synchronize_to_health_threshold: false
                priority: P1
                issue_enabled: true
                threshold_value: "80"
