---
- name: Generate Brownfield SDA Fabric Transits Playbook with Various Filtering Scenarios
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate Brownfield SDA Fabric Transits Playbook
      cisco.dnac.brownfield_sda_fabric_transits_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log_level: DEBUG
        dnac_log: true
        state: gathered
        config:
          # ====================================================================================
          # Scenario 1: Fabric Transits - Fetch All Configurations
          # Tests behavior when no filters are provided
          # ====================================================================================
          # - generate_all_configurations: true

          # ================================================
          # Scenario 2: Fabric Transits - Component Specific Filters
          # Tests behavior when component specific filters are provided
          # ================================================
          # - file_path: "demo.yaml"
          #   component_specific_filters:
          #     components_list: ["sda_fabric_transits"]

          # ================================================
          # Scenario 3: Fabric Transits - Component Specific Filters with Transit Type
          # Tests behavior when component specific filters with transit type are provided
          # ================================================
          # - file_path: "demo1.yaml"
          #   component_specific_filters:
          #     components_list: ["sda_fabric_transits"]
          #     sda_fabric_transits:
          #       - transit_type: "IP_BASED_TRANSIT"

          # ================================================
          # Scenario 4: Fabric Transits - Component Specific Filters with Transit Name
          # Tests behavior when component specific filters with transit name are provided
          # ================================================
          # - file_path: "demo1.yaml"
          #   component_specific_filters:
          #     components_list: ["sda_fabric_transits"]
          #     sda_fabric_transits:
          #       - name: "sample_transit3"

          # ================================================
          # Scenario 5: Fabric Transits - Component Specific Filters with Transit Name and Type
          # Tests behavior when component specific filters with transit name and type are provided
          # ================================================
          # - file_path: "demo1.yaml"
          #   component_specific_filters:
          #     components_list: ["sda_fabric_transits"]
          #     sda_fabric_transits:
          #       - name: "sample_transit2"
          #         transit_type: "IP_BASED_TRANSIT"

          # ================================================
          # Scenario 6: Fabric Transits - Component Specific Filters with Transit Type SDA_LISP_PUB_SUB_TRANSIT
          # Tests behavior when component specific filters with transit type SDA_LISP_PUB_SUB_TRANSIT are provided
          # ================================================
          # - file_path: "demo1.yaml"
          #   component_specific_filters:
          #     components_list: ["sda_fabric_transits"]
          #     sda_fabric_transits:
          #       - transit_type: "SDA_LISP_PUB_SUB_TRANSIT"

          # ================================================
          # Scenario 7: Fabric Transits - Component Specific Filters with Transit Type SDA_LISP_BGP_TRANSIT
          # Tests behavior when component specific filters with transit type SDA_LISP_BGP_TRANSIT are provided
          # ================================================
          - file_path: "demo2.yaml"
            component_specific_filters:
              components_list: ["sda_fabric_transits"]
              sda_fabric_transits:
                - transit_type: "SDA_LISP_BGP_TRANSIT"
