# noqa all
---
- name: Sda fabric
  hosts: dnac_servers
  vars_files:
    - vars/credentials.yml
  gather_facts: false
  tasks:
    - name: Create an sda_fabric
      cisco.dnac.sda_fabric_sites:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_debug: "{{ dnac_debug }}"
        state: present
        payload:
          - siteId: "{{ site_id }}"
            authenticationProfileName: "No Authentication"
            isPubSubEnabled: false
      register: sda_fabric_result

    - name: Show new sda_fabric
      ansible.builtin.debug:
        msg: "{{ sda_fabric_result }}"
      when:
        - sda_fabric_result is defined
