---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: testing wireless design workflow manager
      cisco.dnac.wireless_design_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
        - feature_template_config:
            - clean_air_configuration:
                - design_name: "sample_cleanair_design_24ghz"
                  feature_attributes:
                    radio_band: 2_4GHZ   # enum: 2_4GHZ, 5GHZ, 6GHZ
                    clean_air: true
                    clean_air_device_reporting: true
                    persistent_device_propagation: false
                    description: "CleanAir profile for 2.4GHz office deployment"
                    # Interferers Features (map)
                    interferers_features:
                      ble_beacon: true                     # Only applicable for 2_4GHZ
                      bluetooth_paging_inquiry: false     # Only applicable for 2_4GHZ
                      bluetooth_sco_acl: false            # Only applicable for 2_4GHZ
                      continuous_transmitter: true       # Applicable for 2_4GHZ, 5GHZ, 6GHZ
                      generic_dect: false                 # 2_4GHZ and 5GHZ
                      generic_tdd: false                  # Only 2_4GHZ
                      jammer: false                       # 2_4GHZ and 5GHZ
                      microwave_oven: true                # Only 2_4GHZ
                      motorola_canopy: false              # 2_4GHZ and 5GHZ
                      si_fhss: false                      # 2_4GHZ and 5GHZ
                      spectrum80211_fh: false             # 2_4GHZ only
                      spectrum80211_non_standard_channel: false  # 2_4GHZ and 5GHZ
                      spectrum802154: false               # 2_4GHZ only
                      spectrum_inverted: false            # 2_4GHZ and 5GHZ
                      super_ag: false                     # 2_4GHZ and 5GHZ
                      video_camera: false                 # 2_4GHZ and 5GHZ
                      wimax_fixed: false                  # 2_4GHZ and 5GHZ
                      wimax_mobile: false                 # 2_4GHZ and 5GHZ
                      xbox: false                         # 2_4GHZ only
                  unlocked_attributes:
                    - "clean_air"
                    - "clean_air_device_reporting"
                    - "persistent_device_propagation"
                    - "description"
                    - "interferers_features.ble_beacon"
                    - "interferers_features.continuous_transmitter"
